---
title: "train_xgboost"
author: "Chen, Yanchen YC3373"
date: "November 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(foreach)
  library(doParallel)
train_xgboost <- function(dat_train, label_train, par=NULL){
  
  ### Train a Gradient Boosting Model (GBM) using processed features from training images
  
  ### Input: 
  ###  -  features from LR images 
  ###  -  responses from HR images
  ### Output: a list for trained models
  
  ### load libraries
  library("xgboost")
  
  ### creat model list
  modelList <- list()
  
  ### Train with gradient boosting model
  if(is.null(par)){
    max_depth <- 2
    eta <- 1
  } else {
    max_depth <- par[1]
    eta <- par[2]
  }
  
  ### the dimension of response arrat is * x 4 x 3, which requires 12 classifiers
  ### this part can be parallelized
library(foreach)
library(doParallel)
cl <- makePSOCKcluster(detectCores())
 registerDoParallel(cl)
  modelList <- foreach(i = 1:12, .combine = "cbind") %dopar% {
    library("xgboost")
    c1 <- (i-1) %% 4 + 1
    c2 <- (i-c1) %/% 4 + 1
    featMat <- dat_train[, , c2]
    labMat <- label_train[, c1, c2]
    fit_xgboost <- xgboost(data=featMat, label=labMat,
                           max_depth=max_depth,
                           eta=eta,
                           nthread=2,
                           nrounds=2,
                           objective="reg:linear", 
                           verbose=FALSE)
    modelList[[i]] <- list(fit=fit_xgboost)
  }
  # stopCluster(cl)
  # for (i in 1:12){
  #   ## calculate column and channel
  #   c1 <- (i-1) %% 4 + 1
  #   c2 <- (i-c1) %/% 4 + 1
  #   featMat <- dat_train[, , c2]
  #   labMat <- label_train[, c1, c2]
  #   fit_xgboost <- xgboost(data=featMat, label=labMat,
  #                      max_depth=max_depth,
  #                      eta=eta,
  #                      nthread=2,
  #                      nrounds=2,
  #                      objective="binary:logistic", 
  #                      verbose=FALSE)
  #   modelList[[i]] <- list(fit=fit_xgboost)
  # }
  
  return(modelList)
}
```

```{r}

library(doParallel)
library(foreach)

modelList <- list()
cl <- makePSOCKcluster(detectCores())
 registerDoParallel(cl)
  modelList <- foreach(i = 1:12, .combine = "cbind") %dopar% {
    library("xgboost")
   
  
    c1 <- (i-1) %% 4 + 1
    c2 <- (i-c1) %/% 4 + 1
    featMat <- feat_train[, , c2]
    labMat <- label_train[, c1, c2]
    fit_xgboost <- xgboost(data=featMat, label=labMat,
                           max_depth=2,
                           eta=1,
                           nthread=2,
                           nrounds=2,
                           objective="reg:linear", 
                           verbose=FALSE)
    modelList[[i]] <- list(fit=fit_xgboost)
  }
stopCluster(cl)
train_xgboost(feat_train, label_train)
# view(modelList)




detectCores()
A <- registerDoParallel(cl)

````






























