---
title: "cross_validation"
author: "Chen, Yanchen YC3373"
date: "November 2, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
source("C:/Users/Yanchen/Desktop/GR5243/test.R")

library(doParallel)
library(foreach) 
cl <- makePSOCKcluster(detectCores())
registerDoParallel(cl)
X.train <- feat_train[1:5000,,]
y.train <- label_train[1:5000,,]
max_depth <- c(3,5,7)
eta <- seq(0.1,0.8, by= 0.1)
parms <- expand.grid(max_depth = max_depth, eta = eta)[1:10]
output <- matrix(0, nrow = nrow(parms), ncol = 2, byrow = T)

fold <- caret::createFolds(1:nrow(feat_train[1:5000,,]), k = 3, list = FALSE)
cv.error <- c()

parms.cv <- foreach(i = 1:nrow(parms), .combine = "rbind" ) %do% {
  depth <- parms$max_depth[i]
  et <- parms$eta[i]
  parm <- c(depth, et)

  cv <- foreach(k = 1:max(fold),.combine = "rbind", .inorder = FALSE) %dopar% {
    train.data <- X.train[fold != k,,]
    train.label <- y.train[fold != k,,]
    test.data <- X.train[fold == k,,]
    test.label <- y.train[fold == k,,]
    fit <- train_xgboost(train.data, train.label, par = parm)
    pred <- test(fit, test.data)
    pred <- pred$numericpred
    cv.error[k] <- mean((pred - test.label)^2)
    
   # cv<- list(train.data)
  }
  
  cv.sd <- sd(cv)
  mse <- mean(cv)
  output[i,] <- c(mse, cv.sd)
  colnames(output) <- c("mean", "sd")
}



stopCluster(cl)






```
































